### ISSUE TITLE
Crash on windows when downloading large files

### ISSUE THREAD

**Issue by jpatters** [FabianLars/tauri-plugin-download#29]
I actually have no idea if this plugin is what is causing the issue or not. The only time the app crashes is when it's downloading a file though so I'm taking an educated guess.

I am downloading large files (>2GB) and am getting random crashes. Sometimes it crashes at 2% downloaded, sometimes at 99%, sometimes (but rarely) it doesn't crash at all. 
I have been unable to get any crash logs (not typically a windows developer) other than the exit code from the application which is -1073740940. Google tells me that is a heap corruption error.
I have not experienced this issue on macos. I am not targeting linux so I am unsure if it is happening there.

My download function looks like this and the content is being downloaded from an S3 bucket:

```ts
public async download(progressHandler?: (progress: number, total: number) => void) {
  const dir = await this.dataDir();
  const path = await join(dir, this.BUNDLE_NAME);
  await createDir(dir, { dir: BaseDirectory.Data, recursive: true });

  if (this.latestRelease?.build) {
    let p = 0;
    await download(this.latestRelease.build.buildZipUrl, path, (progress, total) => {
      p = p + progress;
      progressHandler && progressHandler(p, total);
    });
  }
}
```

Any help would be greatly appreciated.

**Comment by FabianLars** [comment]
Hey, thanks for the report and sorry for the delay.

I can't reproduce this at all. I downloaded 10x10GB files with no crashes. So i _think_ it is either related to the file you're downloading (would be weird since we're just reading bytes, and no String stuff), your `progressHandler` (JS heap issue), or something specific to your system maybe.

Can you share a bit more of your project?
Also a screenshot of the error message _may_ help to identify its origin (primarily rust vs webview)

**Comment by jpatters** [comment]
Thanks for taking the time. Good to know that you aren't experiencing issues with it.

A big part of my struggle is that I am not able to see an error. The application crashes and I see nothing. I managed to get the exit code just by running the app via the cli and echoing it after the crash. I can't find any information about further debugging on windows. 

The progress handler code is here (setQueueState is a state function that wraps react useState and uses the tauri-plugin-store lib to persist the current state of the download to disk):

```ts
const updateQueueItem = (
  setQueueState: React.Dispatch<React.SetStateAction<QueueItem[]>>,
  item: QueueItem
) => {
  setQueueState((state) => {
    const newState = [...state];
    const index = newState.findIndex((s) => s.id === item.id);
    if (index === -1) {
      newState.push(item);
    } else {
      newState[index] = { ...newState[index], ...item };
    }
    return newState;
  });
};

...

await experience.download((progress: number) =>
  updateQueueItem(setQueueState, {
    id: experience.id,
    progress: progress,
    status: 'downloading'
  })
);
```

I will start unwinding some things and see if I can pinpoint the issue as well.

**Comment by jpatters** [comment]
It seems your thoughts on the `progressHandler` were correct. It was being called too rapidly. I have rate limited it and now the issue is gone. The fact that I've only observed it on windows was throwing me off. 
Thanks for putting me on the right track.
